---
- name: Deploy Static Web App
  hosts: servers
  become: yes

  tasks:
    - name: Copy script to remote server
      copy:
        src: ./deploy_webapp.sh
        dest: /tmp/deploy_webapp.sh
        mode: 0755

    - name: Execute the script
      shell: /tmp/deploy_webapp.sh

    - name: Remove the script
      file:
        path: /tmp/deploy_webapp.sh
        state: absent
